name: ts_cl

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.12
  - ipykernel
  - pip
  - numpy
  - scikit-learn
  - tslearn
  - fastai::fastai
  - mlflow
  - omegaconf
  - hydra-core
  
  - pip:
    - tsai

