models.model.hidden_size: choice(16, 32, 64, 128, 256)
models.model.rnn_layers: choice(1, 2, 3, 4)
models.model.bias: bool (True, False)
models.model.cell_dropout: float (range(0.0, 0.6, 0.1))
models.model.rnn_dropout: float (range(0.0, 0.6, 0.1))
models.model.bidirectional: bool (True, False)
models.model.fc_dropout: float (range(0.0, 0.6, 0.1))