name: Update README

on:
    push:
        branches:
          - test

jobs:
  update_readme:
    runs-on: ubuntu-latest  # Use an Ubuntu environment

    steps:
      - uses: actions/checkout@v3  # Check out the code

      - name: Update README.md
        run: |
          # Read the contents of best_runs.md
          best_runs_content=$(cat results/best_runs.md)

          # Replace the section in README.md (using delimiter to handle special characters)
          sed -i '//,//c\\
          '"$best_runs_content"'
          \' README.md

          # Commit and push the updated README.md
          git config --global user.email "md.rahman.ce@gmail.com"
          git config --global user.name "Md Mijanur Rahman"
          git commit -m "Automatic README update" README.md
          git push 