name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Replace results in README
        run: |
          results=$(cat results/best_runs.md) # Read the results

          # Replace the results in the README
          awk -v r="$results" '/<!--START-->/ {print; print r; f=1} /<!--END-->/ {f=0} !f' README.md > temp && mv temp README.md

      - name: Commit and push if it changed
        run: |
          git diff
          git config --global user.email "md.rahman.ce@gmail.com"
          git config --global user.name "Md Mijanur Rahman"
          git commit -am "Update README with test results" || exit 0
          git push