name: Update README

on:
  push:
    branches:
      - test2

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Run script
        run: python results/gen_result.py

      - name: Commit results if it changed
        run: |
          git diff --exit-code --quiet results/best_runs.md || (git add results/best_runs.md && git commit -m "Update best runs")

      - name: Replace results in README
        run: |
          results=$(cat results/best_runs.md) # Read the results

          # Replace the results in the README
          awk -v r="$results" '/<!--START-->/ {print; print r; f=1} /<!--END-->/ {f=0} !f' README.md > temp && mv temp README.md

      - name: Commit and push if it changed
        run: |
          git diff
          git config --global user.email "md.rahman.ce@gmail.com"
          git config --global user.name "Md Mijanur Rahman"
          git commit -am "Update README with test results" || exit 0
          git push