name: Update Best Runs

on:
  push:
    branches:
      - test  # Change this to your main branch name if different

jobs:
  update_best_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Read Best Runs Content
        id: read_best_runs
        run: |
          # Read the content of best_runs.md file
          best_run_content=$(cat results/best_runs.md)
          echo "$best_run_content"
      
      - name: Update README.md
        run: |
          # Read the content of README.md
          readme_content=$(cat README.md)
          
          #add the best runs content to the README.md at the end of the file
            echo "$best_run_content" >> README.md
          
          # Check if there are changes in README.md
          if ! git diff --quiet README.md; then
              # Commit and push changes
              git config --global user.name "Md Mijanur Rahman"
              git config --global user.email "md.rahman.ce@gmail.com"
              git add README.md
              git commit -m "Update best runs in README.md"
              git push
          else
              echo "There are no changes in the README.md file"
          fi
