name: Update Best Runs

on:
  push:
    branches:
      - test  # Change this to your main branch name if different

jobs:
  update_best_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Read Best Runs Content
        id: read_best_runs
        run: |
          # Read the content of best_runs.md file
          content=$(cat results/best_runs.md)
          echo "$content"
      
      - name: Update README.md
        run: |
          # Read the content of README.md
          readme_content=$(cat README.md)
          
          echo "Readme Content: $readme_content"

          # Replace content between <!--START--> and <!--END--> with best_runs.md content
          sed -i -e "/<!--START-->/, /<!--END-->/c\<!--START-->\n$readme_content\n<!--END-->" README.md
          
          # Check if there are changes in README.md
          if ! git diff --quiet README.md; then
              # Commit and push changes
              git config --global user.name "Md Mijanur Rahman"
              git config --global user.email "md.rahman.ce@gmail.com"
              git add README.md
              git commit -m "Update best runs in README.md"
              git push
          else
              echo "There are no changes in the README.md file"
          fi
